In [19]:
import numpy as np

In [20]:
# Creating array using python sequence

a = np.array([1,2,3,4,5,6,7,8,9])
b= a[3:6]
print("b: ",b)
b[0]=10  # note here, b is view of the array a so. changes made in one view is reflected in original array.
         # if we want no changes in original array we mus create a copy (copy copies data and metadata)

c= a.copy()   # deep copy
c[2]= 11
print(c.base)  # if base returns none that means it is copy otherwise it is view
print(b.base) # it returns the array whose base it is.
print("c: ",c)
print("a: ",a)

b:  [4 5 6]
None
[ 1  2  3 10  5  6  7  8  9]
c:  [ 1  2 11 10  5  6  7  8  9]
a:  [ 1  2  3 10  5  6  7  8  9]


In [21]:
# attributes of an array 
a.ndim # returns the dimension of an array
a.shape #The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
        # len(a.shape) == a.ndim
a.size  #total number of elements in array 
        # a.size == math.prod(a.shape)
b.flags  #Information about the memory layout of the array.

a.itemsize #Length of one array element in bytes.
a.nbytes   #Total bytes consumed by the elements of the array.
          #a.nbytes == a.itemsize*a.size
a.dtype  #	Data-type of the array's elements.
a.strides # it gives number of  ytes we need to skip to reach next element 



(8,)

In [22]:
# Various array conversion methods 
c.item(1) #Returns one element of the array as a standard Python scalar
d = c.tolist()  # Converts a NumPy array into a nested Python list.
print(type(d))
print(d)

e = a.tobytes() #Returns the raw binary data of the array as bytes.
print(e)

a.tofile("array.txt",sep=',') #Writes array data to a file (binary by default, text if sep is used).

a.dump("a.pkl")   # Saves the array to a file using pickle.
s = a.dumps()     #Returns the pickled array as bytes.
print(s)
g = np.load("a.pkl",allow_pickle =True)  # returns the deserialised pickled data
print(g)

b = a.astype(float) #Returns a copy of the array converted to another data type.
b
a.byteswap(inplace = False) #Swaps byte order (endianness) of elements.

c.setflags(write=False) #sets memory flags like WRITEABLE.
 # c[1]=2 will produce error since array is read only

<class 'list'>
[1, 2, 11, 10, 5, 6, 7, 8, 9]
b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00'
b'\x80\x02cnumpy._core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\t\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03XH\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00q\x11h\x0

In [6]:
# Shape manipulation methods 
g = a.reshape((3,3)).copy()  # gives the new shape to data
g[1,2] =13  # we must use copy() along with the reshape to make chanegs otherwiswe it will  be read only
print(g)


a.resize((9,))   # it changes shape inplace and original array is modified
print(a)
a

g.T   # it transposes i.e the row becomes columns and vice versa or we can say axes are changed

g.swapaxes(1,0)  #Swaps two axes.
g

g.flatten(order = 'C') # Returns a 1D copy of the array.

g.ravel() # returns a 1D view of ana rray

[[ 1  2  3]
 [10  5 13]
 [ 7  8  9]]
[ 1  2  3 10  5  6  7  8  9]


array([ 1,  2,  3, 10,  5, 13,  7,  8,  9])

In [13]:
# item selection and manipulation operaions
g.take(1,axis =1)[2]   # return the value at indices

g.put([2],[41]) # Replaces values at specific positions (flat array)
g

g.repeat(3,axis=0) # repeat elemnts

index = np.array([0, 0, 1])        
q = np.array([10, 20, 30])
r = np.array([100, 200, 300])

np.choose(index, [q, r])   # used to choose between 2 or more arrays 

g.sort(axis=1)  # sort the array 
g
a.sort()
a[::-1]  # numpy doesn't support descending order 

a.argsort() #Returns indices that would sort the array
g.diagonal(offset=0, axis1=0, axis2=1) # gives diagonal , offset determines which diagonal to return  & axes tell the plane from which diagnoal we want
a.partition(2) # Places k-th smallest element in correct position
a


array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [38]:
# Mathematical operations
g.max(axis=1) # Returns the maximum value
g.min(axis=1) # Returns the minimum value

g.argmax(axis=1) # Returns the maximum value index
g.argmin(axis=1) # Returns the minimum value index

b.clip(3,5) # Limits values within a range if value greater than 5 it is set to 5 and value less than 3 is set to 3

b.round(2) # it rounds off value to decimal places
g.trace(offset =1) # returns sum of diagonal
g.sum(axis =1) # returns sum row wise
g.cumsum(axis=1) # returns  cumulative 
g.mean() # returns mean
g.var() # return varience  , it tells the spread of data
g.std() # returns standard deviation 



np.float64(11.30388330520878)

In [16]:
# some other ways of creating an array

k = np.zeros(4,dtype=int)  # used to make an array with all elemnets zero and dtype attribute define the datatype 
k
l = np.ones(4,dtype=int)
l
m = np.empty(4) # used to create an array with random numbersa inside it
m
n = np.arange(1,10,3) # used to create an array with numbers in range of first two arguments and the step size id defined by last argument
n
o = np.linspace(2,3,5)   # it is just like arange b ut it gives evenly spaced values  but unlike arange the stop is included in it
o

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [23]:
# sorting method
names = np.array(['b', 'a', 'b', 'a'])  # it sorts based on first array and if the elements in first array 
                                         #are same then it sorts based on second array
scores = np.array([90, 85, 95, 90])

idx = np.lexsort((scores, names))
idx



array([1, 3, 0, 2])